__base__: sen2venus_exp2_v5.yml

dataset:
  root_path: data/sen2venus
  stats:
    use_minmax: true
    tensor_05m_b2b3b4b8:
      mean: [444.21923828125, 715.9031372070312, 813.4345703125, 2604.867919921875]
      std: [279.85552978515625, 385.3569641113281, 648.458984375, 796.9918212890625]
      min: [-1025.0, -3112.0, -5122.0, -3851.0]
      max: [14748.0, 14960.0, 16472.0, 16109.0]
    tensor_10m_b2b3b4b8:
      mean: [443.78643798828125, 715.4202270507812, 813.0512084960938, 2602.813232421875]
      std: [283.89276123046875, 389.26361083984375, 651.094970703125, 811.5682373046875]
      min: [-848.0, -902.0, -946.0, -323.0]
      max: [19684.0, 17982.0, 17064.0, 15958.0]
  hr_name: tensor_05m_b2b3b4b8
  lr_name: tensor_10m_b2b3b4b8
  collate_fn: mods.v3.collate_fn
  denorm: mods.v3.uncollate_fn
  printable: mods.v3.printable

losses:
  #MSE LOSS
  with_pixel_criterion: true
  with_ssim_criterion: true
  with_cc_criterion: true
  weights:
    pixel: 0.1 
    ssim: 1.0
    cc: 1.0
    moe: 0.2
    kl: 0.5
    entropy: 0.01

optim: 
  learning_rate: 0.0001
  model_betas: [0.9, 0.999]
  model_eps: 0.00000001
  model_weight_decay: 0
  band_corr_lr: 0.00001 # 0.1 * lr
  band_corr_weight_decay: 1e-4
  scheduler:
    type: 'CosineAnnealingLR'
    T_max: 50
    eta_min: 0.000001
    warmup_epochs: 5
 

super_res:
  version: 'FEC-DPS-MOE' # Set the version to use the new model
  model:
    mlp_ratio: 1
    upscale: 2
    in_chans: 4
    MoE_config:
      num_experts: 8
      num_bands: 4
      lora_rank: 4
      lora_alpha: 8.0
      capacity_factor: 1.25
      dct_freq_features: 64 # New parameter for frequency features
      dct_extractor: 'DistortionAware'

metrics:
  upscale_factor: 2

train:
  band_correction_warmup_epochs: 5

visualize:
  input_shape: [4, 128, 128]
